### ISSUE TITLE
IDGen initialization error

### ISSUE THREAD

**Issue by b0c1** [47deg/macroid#71]
Hi guys, I got a strange exception when my application start:
```
    java.lang.NoSuchMethodError: No virtual method Map()Lscala/collection/immutable/Map$; in class Lscala/Predef$; or its super classes (declaration of 'scala.Predef$' appears in /data/app/hu.finesolution.livestream-1/base.apk)
            at macroid.IdGen.<init>(Searching.scala:12)
            at macroid.IdGeneration$class.$init$(Searching.scala:32)
```

This occurs when the application call
```scala
class IdGen(start: Int) extends Dynamic {
  private var ids = Map[String, Int]()
```

My class initialization:
```scala
class MainActivity extends FragmentActivity with Contexts[FragmentActivity] with IdGeneration {
```

I miss something?

Thanks

**Comment by dant3** [comment]
Most likely proguard removed `scala.collection.immutable.Map$`. Try keeping it explicitly in your proguard config.

**Comment by b0c1** [comment]
Thanks...
Now I got another problem... I using Akka and the code inside the withUi call never called....
```scala
 override def receive: Receive = receiveUi andThen {
    case data: List[Test] =>
      log.debug("Got test list:" + data)
      withUi(f => {
        f.receive(data)
      })
```

I try to debug a little but I see attachedUi in FragmentActor is None... I miss something?

**Comment by b0c1** [comment]
Nevermind... I found the error thanks...
