### ISSUE TITLE
Compile Incremental AbstractMethodError: macroid.warts.CheckUi Errors

### ISSUE THREAD

**Issue by rutaihwa** [47deg/macroid#82]
Im experiencing this in subsequent builds once the app has been buit powered off and rebuilt again later.
`(compile:compileIncremental) java.lang.AbstractMethodError: macroid.warts.CheckUi$.apply(Lorg/brianmckenna/wartremover/WartUniverse;)Lscala/reflect/api/Trees$Traverser;`

The full log is something like this I have an intuition that is some cache playing dirty but Im really null in this

`[debug] 	/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/classes:/home/frank/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar
[debug] 	-classpath
[debug] 	/home/frank/Workshop/shop/2seme/android/target/android/intermediates/classes:/home/frank/.android/sbt/exploded-aars/org.macroid-macroid_2.11-2.0.0-M4/org.macroid-macroid_2.11-2.0.0-M4.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-support-v4-23.2.1/com.android.support-support-v4-23.2.1.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-design-23.2.1/com.android.support-design-23.2.1.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-appcompat-v7-23.2.1/com.android.support-appcompat-v7-23.2.1.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-animated-vector-drawable-23.2.1/com.android.support-animated-vector-drawable-23.2.1.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-support-vector-drawable-23.2.1/com.android.support-support-vector-drawable-23.2.1.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-recyclerview-v7-23.2.1/com.android.support-recyclerview-v7-23.2.1.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-cardview-v7-23.2.1/com.android.support-cardview-v7-23.2.1.jar:/home/frank/.android/sbt/exploded-aars/com.fortysevendeg-macroid-extras_2.11-0.2/com.fortysevendeg-macroid-extras_2.11-0.2.jar:/home/frank/.android/sbt/exploded-aars/com.google.android.gms-play-services-base-8.4.0/com.google.android.gms-play-services-base-8.4.0.jar:/home/frank/.android/sbt/exploded-aars/com.google.android.gms-play-services-basement-8.4.0/com.google.android.gms-play-services-basement-8.4.0.jar:/home/frank/.android/sbt/exploded-aars/com.google.android.gms-play-services-maps-8.4.0/com.google.android.gms-play-services-maps-8.4.0.jar:/home/frank/.android/sbt/exploded-aars/com.google.android.gms-play-services-location-8.4.0/com.google.android.gms-play-services-location-8.4.0.jar:/home/frank/.android/sbt/exploded-aars/com.android.support-support-v4-23.2.1/libs/internal_impl-23.2.1.jar:/home/frank/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.11.6.jar:/home/frank/Workshop/tools/Android/Sdk/extras/android/m2repository/com/android/support/support-annotations/23.2.1/support-annotations-23.2.1.jar:/home/frank/.ivy2/cache/org.scala-lang.modules/scala-async_2.11/bundles/scala-async_2.11-0.9.2.jar:/home/frank/.ivy2/cache/org.brianmckenna/wartremover_2.11/jars/wartremover_2.11-0.10.jar:/home/frank/.ivy2/cache/org.scala-lang/scala-compiler/jars/scala-compiler-2.11.0.jar:/home/frank/.ivy2/cache/org.scala-lang.modules/scala-xml_2.11/bundles/scala-xml_2.11-1.0.1.jar:/home/frank/.ivy2/cache/org.scala-lang.modules/scala-parser-combinators_2.11/bundles/scala-parser-combinators_2.11-1.0.1.jar:/home/frank/.ivy2/cache/com.squareup.okhttp/okhttp/jars/okhttp-2.3.0.jar:/home/frank/.ivy2/cache/com.squareup.okio/okio/jars/okio-1.3.0.jar:/home/frank/.ivy2/cache/com.typesafe.play/play-json_2.11/jars/play-json_2.11-2.3.4.jar:/home/frank/.ivy2/cache/com.typesafe.play/play-iteratees_2.11/jars/play-iteratees_2.11-2.3.4.jar:/home/frank/.ivy2/cache/org.scala-stm/scala-stm_2.11/jars/scala-stm_2.11-0.7.jar:/home/frank/.ivy2/cache/com.typesafe/config/bundles/config-1.2.1.jar:/home/frank/.ivy2/cache/com.typesafe.play/play-functional_2.11/jars/play-functional_2.11-2.3.4.jar:/home/frank/.ivy2/cache/com.typesafe.play/play-datacommons_2.11/jars/play-datacommons_2.11-2.3.4.jar:/home/frank/.ivy2/cache/joda-time/joda-time/jars/joda-time-2.3.jar:/home/frank/.ivy2/cache/org.joda/joda-convert/jars/joda-convert-1.6.jar:/home/frank/.ivy2/cache/com.fasterxml.jackson.core/jackson-annotations/bundles/jackson-annotations-2.3.2.jar:/home/frank/.ivy2/cache/com.fasterxml.jackson.core/jackson-core/bundles/jackson-core-2.3.2.jar:/home/frank/.ivy2/cache/com.fasterxml.jackson.core/jackson-databind/bundles/jackson-databind-2.3.2.jar:/home/frank/.ivy2/cache/com.squareup.picasso/picasso/jars/picasso-2.5.0.jar:/home/frank/.ivy2/cache/org.ocpsoft.prettytime/prettytime/jars/prettytime-3.2.7.Final.jar
java.lang.AbstractMethodError: macroid.warts.CheckUi$.apply(Lorg/brianmckenna/wartremover/WartUniverse;)Lscala/reflect/api/Trees$Traverser;
	at org.brianmckenna.wartremover.Plugin$Traverser$$anon$1$$anonfun$go$1$1.apply(Plugin.scala:72)
	at org.brianmckenna.wartremover.Plugin$Traverser$$anon$1$$anonfun$go$1$1.apply(Plugin.scala:72)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.brianmckenna.wartremover.Plugin$Traverser$$anon$1.go$1(Plugin.scala:72)
	at org.brianmckenna.wartremover.Plugin$Traverser$$anon$1.apply(Plugin.scala:74)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$applyPhase$1.apply$mcV$sp(Global.scala:440)
	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:431)
	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:440)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
	at scala.tools.nsc.Global$GlobalPhase$$anonfun$run$1.apply(Global.scala:398)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:398)
	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1501)
	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1486)
	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1481)
	at scala.tools.nsc.Global$Run.compile(Global.scala:1582)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:116)
	at xsbt.CachedCompiler0.run(CompilerInterface.scala:95)
	at xsbt.CompilerInterface.run(CompilerInterface.scala:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.compiler.AnalyzingCompiler.call(AnalyzingCompiler.scala:101)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:47)
	at sbt.compiler.AnalyzingCompiler.compile(AnalyzingCompiler.scala:41)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply$mcV$sp(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler$$anonfun$compileScala$1$1.apply(MixedAnalyzingCompiler.scala:51)
	at sbt.compiler.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:75)
	at sbt.compiler.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:50)
	at sbt.compiler.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:65)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$$anonfun$compileInternal$1.apply(IncrementalCompiler.scala:160)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:66)
	at sbt.inc.IncrementalCompile$$anonfun$doCompile$1.apply(Compile.scala:64)
	at sbt.inc.IncrementalCommon.cycle(IncrementalCommon.scala:31)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:62)
	at sbt.inc.Incremental$$anonfun$1.apply(Incremental.scala:61)
	at sbt.inc.Incremental$.manageClassfiles(Incremental.scala:89)
	at sbt.inc.Incremental$.compile(Incremental.scala:61)
	at sbt.inc.IncrementalCompile$.apply(Compile.scala:54)
	at sbt.compiler.IC$.compileInternal(IncrementalCompiler.scala:160)
	at sbt.compiler.IC$.incrementalCompile(IncrementalCompiler.scala:138)
	at sbt.Compiler$.compile(Compiler.scala:128)
	at sbt.Compiler$.compile(Compiler.scala:114)
	at sbt.Defaults$.sbt$Defaults$$compileIncrementalTaskImpl(Defaults.scala:814)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:805)
	at sbt.Defaults$$anonfun$compileIncrementalTask$1.apply(Defaults.scala:803)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (compile:compileIncremental) java.lang.AbstractMethodError: macroid.warts.CheckUi$.apply(Lorg/brianmckenna/wartremover/WartUniverse;)Lscala/reflect/api/Trees$Traverser;`

**Comment by rutaihwa** [comment]
Solved with using `compilerPlugin("org.brianmckenna" %% "wartremover" % "0.10")` instead of the latest somehow. Works for me at the moment.
